# SE
CMPPDS:PFN=30,NAM=MASC_B,SEQ="0??10517",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="0??10517",ISA=0,ISB=S_INF,QTS=0,CRN=1,CRR=0;

# FIXO LC
CMPPDS:PFN=30,NAM=MASC_B,SEQ="2",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="2",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

CMPPDS:PFN=30,NAM=MASC_B,SEQ="3",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="3",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

CMPPDS:PFN=30,NAM=MASC_B,SEQ="4",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="4",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

CMPPDS:PFN=30,NAM=MASC_B,SEQ="5",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="5",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

# FIXO LC A COBRAR
CMPPDS:PFN=30,NAM=MASC_B,SEQ="9090",ICC=SIM,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=3,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="9090",ISA=0,ISB=2,QTS=2,CRN=2,CRR=0;

# LD
CMPPDS:PFN=30,NAM=MASC_B,SEQ="0",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="0",ISA=0,ISB=S_INF,QTS=0,CRN=3,CRR=0;

# LD A COBRAR
CMPPDS:PFN=30,NAM=MASC_B,SEQ="90",ICC=SIM,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=16,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="90",ISA=0,ISB=S_INF,QTS=0,CRN=4,CRR=0;
MMPPDS:PFN=30,NAM=MASC_B,SEQ="90",POP=2;

# CNG
CMPPDS:PFN=30,NAM=MASC_B,SEQ="0?00",ICC=NAO,ICI=SIM,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=SIM,MPO=S_INF,ICN=NAO;

# VC1
CMPPDS:PFN=30,NAM=MASC_B,SEQ="0??2",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="0??2",ISA=0,ISB=S_INF,QTS=0,CRN=1,CRR=0;

CMPPDS:PFN=30,NAM=MASC_B,SEQ="0??3",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="0??3",ISA=0,ISB=S_INF,QTS=0,CRN=1,CRR=0;

CMPPDS:PFN=30,NAM=MASC_B,SEQ="0??4",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="0??4",ISA=0,ISB=S_INF,QTS=0,CRN=1,CRR=0;

CMPPDS:PFN=30,NAM=MASC_B,SEQ="0??5",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="0??5",ISA=0,ISB=S_INF,QTS=0,CRN=1,CRR=0;

CMPPDS:PFN=30,NAM=MASC_B,SEQ="0??9",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=S_INF,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="0??9",ISA=0,ISB=S_INF,QTS=0,CRN=1,CRR=0;

# VC1 A COBRAR
CMPPDS:PFN=30,NAM=MASC_B,SEQ="90??9",ICC=SIM,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=3,ICN=NAO;
MMPPDS:PFN=30,NAM=MASC_B,SDN=B_BUSCA,SEQ="90??9",ISA=0,ISB=S_INF,QTS=0,CRN=2,CRR=0;