# SE
CMPPDS:PFN=31,NAM=MASC_B,SEQ="10315",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=5,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="10315",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

CMPPDS:PFN=31,NAM=MASC_B,SEQ="10615",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=5,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="10615",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

CMPPDS:PFN=31,NAM=MASC_B,SEQ="1058",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=2,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="1058",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

# FIXO LOCAL
CMPPDS:PFN=31,NAM=MASC_B,SEQ="2",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=5,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="2",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

CMPPDS:PFN=31,NAM=MASC_B,SEQ="3",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=5,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="3",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

CMPPDS:PFN=31,NAM=MASC_B,SEQ="4",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=5,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="4",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

CMPPDS:PFN=31,NAM=MASC_B,SEQ="5",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=5,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="5",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

# FIXO LOCAL A COBRAR
CMPPDS:PFN=31,NAM=MASC_B,SEQ="9090",ICC=SIM,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=13,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="9090",ISA=0,ISB=2,QTS=2,CRN=2,CRR=0;

# CNG 
CMPPDS:PFN=31,NAM=MASC_B,SEQ="0?00",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=SIM,MPO=S_INF,ICN=NAO;

# LONGA DISTANCIA
CMPPDS:PFN=31,NAM=MASC_B,SEQ="0",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=2,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="0",ISA=0,ISB=S_INF,QTS=0,CRN=3,CRR=0;

# LONGA DISTANCIA A COBRAR
CMPPDS:PFN=31,NAM=MASC_B,SEQ="90",ICC=SIM,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=16,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="90",ISA=0,ISB=S_INF,QTS=0,CRN=4,CRR=0;

# VC1
CMPPDS:PFN=31,NAM=MASC_B,SEQ="9",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=2,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="9",ISA=0,ISB=S_INF,QTS=2,CRN=0,CRR=0;

# VC1 A COBRAR
CMPPDS:PFN=31,NAM=MASC_B,SEQ="90909",ICC=SIM,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=17,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="90909",ISA=0,ISB=2,QTS=2,CRN=2,CRR=0;