# LONGA DISTANCIA TRANSPORTE

CMPPDS:PFN=31,NAM=MASC_B,SEQ="660",ICC=NAO,ICI=NAO,ICL=NAO,ICE=NAO,IUP=NAO,ISM=NAO,ING=NAO,MPO=2,ICN=NAO;
MMPPDS:PFN=31,NAM=MASC_B,SDN=B_BUSCA,SEQ="660",ISA=0,ISB=S_INF,QTS=0,CRN=5,CRR=0;